package cc.kinisi.geo.data.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ApiToken was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ApiToken extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String STATUS_PROPERTY = "status";
    public static final String TOKEN_PROPERTY = "token";

    public static final String ID_PK_COLUMN = "id";

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setStatus(Short status) {
        writeProperty("status", status);
    }
    public Short getStatus() {
        return (Short)readProperty("status");
    }

    public void setToken(String token) {
        writeProperty("token", token);
    }
    public String getToken() {
        return (String)readProperty("token");
    }

}
