package cc.kinisi.geo.data.auto;

import org.apache.cayenne.CayenneDataObject;

import cc.kinisi.geo.data.DeviceConfiguration;

/**
 * Class _DeviceInterface was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DeviceInterface extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String DEVICE_ID_PROPERTY = "deviceId";
    public static final String NAME_PROPERTY = "name";
    public static final String DEVICE_CONFIGURATION_PROPERTY = "deviceConfiguration";

    public static final String ID_PK_COLUMN = "id";

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setDeviceId(String deviceId) {
        writeProperty("deviceId", deviceId);
    }
    public String getDeviceId() {
        return (String)readProperty("deviceId");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setDeviceConfiguration(DeviceConfiguration deviceConfiguration) {
        setToOneTarget("deviceConfiguration", deviceConfiguration, true);
    }

    public DeviceConfiguration getDeviceConfiguration() {
        return (DeviceConfiguration)readProperty("deviceConfiguration");
    }


}
